### ISSUE TITLE
Linker errors on Rust stable/nightly

### ISSUE THREAD

**Issue by koesie10** [flybywiresim/msfs-rs#8]
I'm trying to compile the `log` example on the latest stable Rust. It works fine on Rust 1.50.0, but when I try to compile it using `cargo build --target wasm32-wasi --release` on either stable or nightly, I get errors about duplicate or mismatched symbols.

On stable the error is:
```
  = note: rust-lld: error: function signature mismatch: __wasilibc_find_relpath
          >>> defined as (i32, i32, i32, i32) -> i32 in /home/koen/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-wasi/lib/liblibc-dd6fd16fbeb0b6c9.rlib(preopens.o)
          >>> defined as (i32, i32) -> i32 in /home/koen/Projects/msfs-rs/examples/log/target/wasm32-wasi/release/deps/libmsfs-f86d96b204d1553c.rlib(msfs-f86d96b204d1553c.msfs.75x4tcz7-cgu.7.rcgu.o)
```

On nightly the error is:
```
  = note: rust-lld: error: duplicate symbol: __wasilibc_find_relpath
          >>> defined in /home/koen/Projects/msfs-rs/examples/log/target/wasm32-wasi/release/deps/libmsfs-bcd1bbed38b8c776.rlib(msfs-bcd1bbed38b8c776.msfs.dlh6xg85-cgu.10.rcgu.o)
          >>> defined in /home/koen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-wasi/lib/liblibc-8936f5648559be90.rlib(preopens.o)
```

I also tried setting the `-Ctarget-feature=-crt-static` flag on the latest nightly on my own project, but then I get the error:

```
  = note: rust-lld: error: unable to find library -lc
```

If I then add `cargo:rustc-link-search=native=$MSFS_SDK/WASM/wasi-sysroot/lib/wasm32-wasi` to my build script, I again get a duplicate symbol error:

```
  = note: rust-lld: error: duplicate symbol: __wasilibc_find_relpath
          >>> defined in /home/koen/myproject/target/wasm32-wasi/release/deps/libmsfs-04ce17aee63bcb3e.rlib(msfs-04ce17aee63bcb3e.msfs.7i63n86g-cgu.10.rcgu.o)
          >>> defined in /home/koen/myproject/msfs-sdk/WASM/wasi-sysroot/lib/wasm32-wasi/libc.a(libpreopen.o)
```

Rust 1.50.0 works fine. Is this something on my end or is it something that needs to be fixed in msfs-rs?

**Comment by devsnek** [comment]
This is due to a hack we use to work around a bug in the flight simulator. For the moment, this package needs 1.50.0.

**Comment by koesie10** [comment]
Thank you, should I keep this issue open to keep track of it?

**Comment by devsnek** [comment]
sure
